### ISSUE TITLE
No focuskeyword imported

### ISSUE THREAD

**Issue by kornflex** [jcollings/importwp-yoast-seo#1]
Hello,

I have added and filled the "Focus Keyphrase:" in importWP : 
https://pasteboard.co/JuHIDR6.png

but my post doesn't put the focus keyword :/ 
https://pasteboard.co/JuHIV7j.png

Could you please tell me what's the right field ?

Thank you.

**Comment by jcollings** [comment]
Hi @kornflex ,

Which which version of YoastSEO are you using, and what are you trying to import, e.g. post, page, taxonomy, user, or custom post_type?

**Comment by kornflex** [comment]
Hello

Thank you for your help.
I have Yoast Version 15.0

ImportWP Yoast : Version 2.0.0 ( but downloaded 2.0.22 release )

I'm trying to import Post.

I'm wrong, it's not only the focus keyword, it's all the SEO :  description, facebook/twitter title& desc...

**Comment by kornflex** [comment]
Hello,

I still have the same problem :/ I don't know where I'm wrong.

Can you help me ?

Thank you

**Comment by jcollings** [comment]
Hi, @kornflex 

I have just tested this uisng ImportWP 2.1.1 and ImportWP PRO 2.1.1 , along with importwp-yoast 2.0.23 with both xml and csv feeds, and yoast data is being imported, without being able to replicate the issue it is hard to resolve.

Are you able to replicate the issue if you install a fresh copy of wordpress using the default theme, and only have importwp, yoast-seo, and importwp-yoast-seo installed?

James

**Comment by kornflex** [comment]
Thank you for your help !

I found the problem : Rehub importWP addon ( importwp-rhaddon Version 1.4 )
If I disable it Yoast addon is working.
When enable : Yoast keyword doesn't work :/
